### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by andriycraft**

### CODE REVIEW

**Comment by andriycraft** [comment]
Who put package-lock.json in .gitignore
dxsfdffds

**Comment by VaxPex** [comment]
> Who put package-lock.json into .gitignore? dxsfdffds

It auto generate why i dont want 2?

**Comment by VaxPex** [comment]
And i will check what u did

**Comment by VaxPex** [comment]
It was good until u copied the player class and pasted it at the server class

**Comment by andriycraft** [comment]
oops

**Comment by VaxPex** [comment]
the bug of the BlueBird.json is not coping is by the raknet starting before it get copied

**Comment by VaxPex** [comment]
It only needs test now

**Comment by andriycraft** [comment]
ok

**Comment by andriycraft** [comment]
image

it works

**Comment by VaxPex** [comment]
Onlinemod?

**Comment by andriycraft** [comment]
works!

[11:31:59] WARNING > Steve tried to join without XUID

**Pull request merged**
