### PR TITLE
Add new packets

### PR DESCRIPTION
**Pull request by SkyderG**

### CODE REVIEW

**Comment by Liqee431** [comment]
Does it work?

**Comment by SkyderG** [comment]
Basically I just added these packets, because before, i tried to enter the server and it appeared "unhandled packet", and so I decided to add the listed packets to see what happened, but I got disconnected from the server. Maybe these packets can help in the development.

**Comment by VaxPex** [comment]
its fixed the disconnection

**Comment by SkyderG** [comment]
ok, but the packets can be introduced with the project or do you need something else to implement?

**Comment by Liqee431** [comment]
Merge this pull requesr @VaxPex this is helpful for creating custom commands and plugins

**Comment by Liqee431** [comment]
If bluebird allows to make plugins in the future

**Comment by SkyderG** [comment]
Yes, this PR can be very useful for the project, or not. I will wait for an answer about.

**Pull request merged**
