### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by andriycraft**

### CODE REVIEW

**Comment by andriycraft** [comment]
So now i will make a pr everytime i see any ugly code

**Comment by VaxPex** [comment]
> So now i will make a pr everytime i see any ugly code

no need

**Review by NhanAZ — COMMENTED** [review]
Looks like they're rewriting the code. PR at this point can cause conflicts?

**Comment by andriycraft** [comment]
> Looks like they're rewriting the code. PR at this point can cause conflicts?

no

**Comment by andriycraft** [comment]
> > So now i will make a pr everytime i see any ugly code
> 
> no need

need

**Comment by andriycraft** [comment]
then im closing this pr

**Pull request closed without merging**
