### PR TITLE
Added testing server to readme.md

### PR DESCRIPTION
**Pull request by andriycraft**

### CODE REVIEW

**Comment by andriycraft** [comment]
@VaxPex @MFDGaming

**Comment by VaxPex** [comment]
is the server as? cuz my ping is 2550990914391849

**Comment by andriycraft** [comment]
> is the server as? cuz my ping is 2550990914391849

your internet connection is trash

**Comment by andriycraft** [comment]
testing server doesnt work anymore

**Comment by AnyBananaGAME** [comment]
Do you use free trials to host a server-

**Comment by andriycraft** [comment]
no

**Comment by AnyBananaGAME** [comment]
image
image
image

**Comment by VaxPex** [comment]
fuck u nigger

**Comment by VaxPex** [comment]
ima block u if u spam again

**Pull request closed without merging**
